name: letsdo
base: core20
version: '1.7.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: The time-tracker for command-line
description: |
  Letsdo helps you to be more focused and productive, tracking your TODO
  and the time you spend working on them.
grade: devel
confinement: strict

apps:
    lets:
        command: bin/letsdo
        plugs:
            - home
        aliases:
            - letsdo
            - lets

parts:
  python39:
    source: https://www.python.org/ftp/python/3.9.13/Python-3.9.13.tgz
    source-type: tar
    source-checksum: md5/5e2411217b0060828d5f923eb422a3b8
    plugin: autotools
    configflags:
      - --prefix=/usr
      # Enabling this will make the build times go up significantly because it
      # turns on link time optimizations and profile guided optimizations.
      #
      # For PGO, python is compiled twice. Once to collect profiling data (by
      # from running all UTs) and once to create an optimized build based on
      # that data.
      #
      # Unfortunately, one of the unit tests, test_socket, hangs for some
      # reason and it seems to be a known issue. For now just disable
      # optimizations as a workaround.
      #
      # - --enable-optimizations
    build-packages:
      # not needed: tk-dev
      - libbz2-dev
      - libexpat1-dev
      - libffi-dev
      - libgdbm-dev
      - liblzma-dev
      - libncurses5-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libzip-dev
      - uuid-dev
    stage-packages:
      # not needed: tk8.6
      - libbz2-1.0
      - libexpat1
      - libffi6
      - libgdbm3
      - liblzma5
      - libncurses5
      - libreadline6
      - libsqlite3-0
      - libssl1.0.0
      - libzip4
      - uuid-runtime
    override-stage: |
      # We want the latest pip to be able to install pyproject.toml based projects
      PYTHONUSERBASE="$SNAPCRAFT_PART_INSTALL/usr" python3.9 -m pip install --user --upgrade pip wheel

      # Apply the same shebang rewrite as done by snapcraft
      find $SNAPCRAFT_PART_INSTALL/usr/bin/ -maxdepth 1 -mindepth 1 -type f -executable -exec \
        sed -i                                                                                \
          "s|^#!${SNAPCRAFT_PART_INSTALL}/usr/bin/python3.9$|#!/usr/bin/env python3|" {} \;

      snapcraftctl stage
    filesets:
      exclusion:
        - -etc
        - -lib/systemd
        - -usr/bin/2to3
        - -usr/bin/2to3-3.9
        - -usr/bin/deb-systemd-helper
        - -usr/bin/deb-systemd-invoke
        - -usr/bin/easy_install-3.9
        - -usr/bin/idle3
        - -usr/bin/idle3.9
        - -usr/bin/pip3
        - -usr/bin/pip3.9
        - -usr/bin/pydoc3
        - -usr/bin/pydoc3.9
        - -usr/bin/python3.9-config
        - -usr/bin/python3-config
        - -usr/bin/uuidgen
        - -usr/include
        - -usr/lib/*.a
        - -usr/lib/pkgconfig
        - -usr/lib/python3.9/test
        - -usr/sbin
        - -usr/share
        - -var
    prime:
      - "$exclusion"
  lets:
    # See 'snapcraft plugins'
    source: https://github.com/clobrano/letsdo.git
    plugin: python
    python-version: python3
    requirements: requirements.txt


