name: letsdo
base: core24
platforms:
  amd64:
version: '2.0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: The time-tracker for command-line
description: |
  Letsdo helps you to be more focused and productive, tracking your TODO
  and the time you spend working on them.
grade: devel
confinement: strict

apps:
    lets:
        command: bin/lets
        plugs:
            - home
        aliases:
            - letsdo
            - lets

parts:
  lets:
    plugin: python
    requirements:
      - requirements.txt
    source: https://github.com/clobrano/letsdo.git

