name: letsdo
version: '0.5.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: The time-tracker for command-line
description: |
  Letsdo helps you to be more focused and productive, tracking your TODO
  and the time you spend working on them.
grade: devel
confinement: strict

apps:
    lets:
        command: bin/letsdo
        plugs:
            - home
        aliases:
            - letsdo
            - lets

parts:
  lets:
    # See 'snapcraft plugins'
    source: https://github.com/clobrano/letsdo.git
    plugin: python
    python-version: python3
    requirements: requirements.txt


